[kojira]
; For user/pass authentication
user=kojira
password=kojira

; The URL for the koji hub server
server=http://hub/kojihub

; The directory containing the repos/ directory
topdir=/mnt/koji

; Logfile
logfile=/var/log/kojira.log
